### ISSUE TITLE
FFTW3 version?

### ISSUE THREAD

**Issue by FFY00** [myriadrf/lime-tools#1]
Which version of `FFTW3` was used to develop this? I am trying to build with `FFTW3 3.3.8` and I get the following error.

```
src/LimeMon.cpp: In function ‘void Init()’:
src/LimeMon.cpp:185:29: error: cannot convert ‘__complex__ double*’ to ‘double (*)[2]’
  pfft=fftw_plan_dft_1d(NFFT,in,out,FFTW_FORWARD,FFTW_ESTIMATE);
```

```
src/LimeScan.cpp: In function ‘void Init()’:
src/LimeScan.cpp:187:29: error: cannot convert ‘__complex__ double*’ to ‘double (*)[2]’
  pfft=fftw_plan_dft_1d(NFFT,in,out,FFTW_FORWARD,FFTW_ESTIMATE);
```

**Comment by IgnasJarusevicius** [comment]
The problem should be solved by c44461aea16293dd5261281142b (added pointer cast).

**Comment by FFY00** [comment]
Thank you!

I released a package on Arch's AUR repository. When you add release (tag/github release) I will release an non `-git` version of the package.

https://aur.archlinux.org/packages/lime-tools-git/
